export default {
  'Wenchao Li': 'https://wenchao.li',
  'Yingcai Wu': 'http://www.ycwu.org',
  'Zhan Wang': 'https://zhanwang071.github.io',
  'Yun Wang': 'https://www.microsoft.com/en-us/research/people/wangyun/',
  'Liwenhan Xie': 'https://shellywhen.github.io/',
  'Siming Chen': 'http://simingchen.me/',
  'Haidong Zhang': 'https://www.microsoft.com/en-us/research/people/haizhang/',
  'Huamin Qu': 'http://www.huamin.org/',
  'Zikun Deng': 'https://zkdeng.org/',
  'Xiao Xie': 'https://ssxiexiao.github.io/',
  'Guodao Sun': 'https://godoorsun.org/',
  'Mingliang Xu':
    'https://scholar.google.com.hk/citations?user=u-8x34cAAAAJ&hl=zh-CN',
  'Shuhan Liu': 'https://scholar.google.com/citations?user=ApD3iicAAAAJ&hl=en',
  'Haoran Xu': 'https://ryanxhr.github.io/',
  'Xiangyu Zhu':
    'https://scholar.google.com.hk/citations?user=OanBHCwAAAAJ&hl=zh-CN',
  'Xianyuan Zhan': 'https://zhanxianyuan.xyz/',
  'Ran Chen':
    'https://crcrcry.notion.site/crcrcry/Ran-CHEN-6853eea1a35e4738aaf15ba570b92716',
  'Yanwei Huang': 'https://yhuang.top/',
  'Xinhuan Shu': 'https://shuxinhuan.github.io/',
  'Jiayi Zhou':
    'https://scholar.google.com/citations?user=3HqYcs4AAAAJ&hl=zh-CN',
  'Heming Zhu': 'https://people.mpi-inf.mpg.de/~hezhu/',
  'Dongyu Liu': 'https://dongyu.tech/',
  'Yuhong Li': 'https://colfire.github.io/',
  'Jie Bao': 'https://scholar.google.com.hk/citations?user=r0rRxncAAAAJ&hl=en',
  'Yu Zheng': 'http://urban-computing.com/yuzheng',
  'Jingmin Chen':
    'https://scholar.google.com/citations?user=KZk0lvMAAAAJ&hl=en',
  'Tobias Schreck': 'https://www.tugraz.at/institute/cgv/Schreck',
  'Dazhen Deng': 'https://dengdazhen.github.io/',
  'Tan Tang': 'https://tantang.org/',
  'Yue Yu': 'https://bruceyyu.github.io/',
  'Yifang Wang': 'https://wangyifang.top/',
  'Qisen Yang': 'https://qs-yang.github.io/',
  'Yongjun Zhang': 'https://yongjunzhang.com/',
  'Junxiu Tang': 'https://ahugh19.github.io/',
  'Siwei Fu': 'https://fusiwei339.bitbucket.io/',
  'Yuxuan Liang': 'https://yuxuanliang.com/',
  'Lingyun Yu': 'https://yulingyun.com/',
  'Yuhua Zhou':
    'https://scholar.google.com/citations?user=dzOBRToAAAAJ&hl=zh-CN',
  'Wei Chen': 'http://www.cad.zju.edu.cn/home/chenwei/',
  'Fangkai Yang':
    'https://www.microsoft.com/en-us/research/people/fangkaiyang/',
  'Jue Zhang': 'https://www.microsoft.com/en-us/research/people/juezhang/',
  'Lu Wang': 'https://scholar.google.com/citations?hl=en&user=hqlU92YAAAAJ',
  'Bo Qiao': 'https://www.microsoft.com/en-us/research/people/boqiao/',
  'Qingwei Lin': 'https://www.microsoft.com/en-us/research/people/qlin/',
  'Dongmei Zhang': 'https://www.microsoft.com/en-us/research/people/dongmeiz/',
  'Weiwei Cui': 'https://www.microsoft.com/en-us/research/people/weiweicu/',
  'Yunfan Zhou': 'https://zyfzd123.github.io/',
  'Lingyu Meng': 'https://kevinmeng49.github.io/',
  'Zhongsu Luo': 'https://zhongsuluo.github.io/',
  'Kai Xiong': 'https://xkkevin.github.io/',
  'Yongheng Wang':
    'https://en.zhejianglab.com/institutescenters/Faculty/202112/t20211209_2924.shtml',
} as { [key: string]: string }
